### ISSUE TITLE
Compilation error, tools

### ISSUE THREAD

**Issue by Alejo1982** [cosmo-epfl/sketchmap#4]
good day
i am compiling sketchmap
when i type make and press enter, after a few seconds i get:

    ...
    ...
    ...
    /home/alejo/Downloads/sketchmap/libs/liblinalg.cpp:314: undefined reference to `dgeev_'
    ../libs//libtoolbox.a(liblinalg.o): In function `toolbox::EigenSolverSym(toolbox::FMatrix<double> const&, toolbox::FMatrix<double>&, std::valarray<double>&, toolbox::LAEigenMode, double, double)':
    /home/alejo/Downloads/sketchmap/libs/liblinalg.cpp:57: undefined reference to `dsyevx_'
    /home/alejo/Downloads/sketchmap/libs/liblinalg.cpp:40: undefined reference to `dsyev_'
    /home/alejo/Downloads/sketchmap/libs/liblinalg.cpp:40: undefined reference to `dsyev_'
    collect2: error: ld returned 1 exit status
    Makefile:24: recipe for target '../bin/dimdist' failed
    make: *** [../bin/dimdist] Error 1
    make: Leaving directory '/home/alejo/Downloads/sketchmap/tools'

how can i solve it?
thank you and cheers

**Comment by ceriottm** [comment]
Did you fix this? Perhaps mentioning how would help others

**Comment by Alejo1982** [comment]
thank you professor Michele Ceriotti, my initial comment was modified and included how it was solved.
